# @package _global_
cluster:
  _target_: dask_jobqueue.SLURMCluster
  queue: normal
  #  account: myaccount
  cores: 1
  memory: 1 GB
  walltime: 00:30:00
  processes: 1
  log_directory: tmp/smac_dask_slurm
  n_workers: ${hydra.sweeper.scenario.n_workers}
