# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort hydra_smac_sweeper
        files: hydra_hydra_smac_sweeper_sweeper
        exclude: "scripts|tests"

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black hydra_smac_sweeper
        files: hydra_smac_sweeper
        exclude: "scripts|tests"

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: pydocstyle hydra_smac_sweeper
        files: hydra_smac_sweeper
        exclude: "scripts|tests"
        additional_dependencies: ["toml"]  # Needed to parse pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        name: mypy hydra_smac_sweeper
        files: hydra_smac_sweeper
        exclude: "scripts|tests"

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 hydra_smac_sweeper
        files: hydra_smac_sweeper
        exclude: "scripts|tests"
