defaults:
  - override hydra/sweeper: SMAC
  - override hydra/launcher: submitit_smac_slurm

hydra:
  launcher:
    partition: cpu_normal
  sweeper:
    n_jobs: 1
    seed: 42
    scenario:
      run_obj: quality
      deterministic: true
#      wallclock_limit: 60
      runcount_limit: 50
    intensifier:
      initial_budget: 1
      max_budget: 1
    search_space:
      hyperparameters:
        x0:
          type: uniform_float
          lower: -5
          upper: 10
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 15
          log: false
          default_value: 2
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

x0: 3
x1: 4

spurious_var: 3.14