defaults:
  - override hydra/sweeper: SMAC

cluster:
  _target_: dask_jobqueue.SLURMCluster
  queue: cpu_short
  #  account: myaccount
  cores: 1
  memory: 1 GB
  walltime: 00:30:00
  processes: 1
  log_directory: tmp/smac_dask_slurm

hydra:
#  launcher:
#    partition: cpu_short
#    cpus_per_task: 1
#    mem_gb: 1
#    gres: null
#    timeout_min: 10
  sweeper:
    scenario:
      seed: 42
      n_trials: 40
      deterministic: true
      n_workers: 3
    smac_kwargs:
      dask_client:
        _target_: dask.distributed.Client
        address: ${create_cluster:${cluster},${hydra.sweeper.scenario.n_workers}}
    search_space:  # TODO adjust search space
      hyperparameters:
        x0:
          type: uniform_float
          lower: -5
          upper: 10
          log: false
        x1:
          type: uniform_float
          lower: 0
          upper: 15
          log: false
          default_value: 2
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}

x0: 3
x1: 4

spurious_var: 3.14