defaults:
  - override hydra/sweeper: SMAC

smac:
  search_space:
    hyperparameters:
      x0:
        type: uniform_float
        lower: -5.5
        upper: 5.5
        log: false
      x1:
        type: uniform_float
        lower: 1e-3
        upper: 5
        log: true
        default_value: 2